### ISSUE TITLE
Unit test is failing, but build reporting success

### ISSUE THREAD

**Issue by dprothero** [TwilioDevEd/lead-alerts-flask#2]
Even though the Travis CI build is reporting a success, if you look at the log, there is a failed unit test...

```
======================================================================
FAIL: test_post_to_notifications_should_send_a_message (tests.views_tests.ViewsTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/home/travis/build/TwilioDevEd/lead-alerts-flask/tests/views_tests.py", line 23, in test_post_to_notifications_should_send_a_message
    'New lead received for house title. Call name at phone. Message message')
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/mock/mock.py", line 925, in assert_called_with
    raise AssertionError('Expected call: %s\nNot called' % (expected,))
AssertionError: Expected call: send_message('New lead received for house title. Call name at phone. Message message')
Not called
```

**Comment by atbaker** [comment]
@dprothero - Good catch. Looks like this repo has the same mistake I made in a personal repo recently.

You can see the fix here: https://github.com/atbaker/anti-voicemail/commit/efc9bc6e8628b3e20e521413b1111f296ac63bd3

Any interest in writing a little Python? If not, I'll happily fix it myself. 

Whoever works on it should also do a quick check of our other Flask repos and make sure they're okay.

**Comment by dprothero** [comment]
@abaker I'll take a stab at it.

**Comment by dprothero** [comment]
@atbaker Made the change and that worked to cause the build to fail. I'm not, however, sure why the unit test is failing. It passes locally, it only fails on Travis. I'll poke around to see if I can debug it.

**Comment by dprothero** [comment]
@atbaker OK, I found the problem. It wanted the TWILIO_ACCOUNT_SID and TWILIO_AUTH_TOKEN environment variables. I just gave them dummy values in .travis.yml. Want to +1 and merge PR #3 for me?

**Comment by atbaker** [comment]
Merged and the build is passing! Thanks @dprothero
